[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/expositions/index.html"
to = "/inspirations/"

[[redirects]]
from = "/personnes/equipe-editoriale/index.html"
to = "/qui-sommes-nous-1/equipe-editoriale/"

[[redirects]]
from = "/expertises/pierre-yves-legrand/index.html"
to = "/qui-sommes-nous-1/pierre-yves-legrand/"

[[redirects]]
from = "/pierre-yves-legrand/index.html"
to = "/qui-sommes-nous-1/pierre-yves-legrand/"

[[redirects]]
from = "/expositions/archives-expositions/index.html"
to = "/inspirations/archives-expositions/"

[[redirects]]
from = "/references/index.html"
to = "/actualites/"

[[redirects]]
from = "/test/index.html"
to = "/nos-metiers/test/"

[[redirects]]
from = "/personnes/index.html"
to = "/qui-sommes-nous-1/"

[[redirects]]
from = "/expertises-1/index.html"
to = "/expertises/"

