[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/nos-metiers/accompagnement-individuel-1/mentorat/index.html"
to = "/nos-metiers/accompagnement-individuel-1/mentor/"

[[redirects]]
from = "/expositions/index.html"
to = "/inspirations/"

[[redirects]]
from = "/nos-metiers/transformation-des-organisations/facilitateur-devenements-professionnels/index.html"
to = "/nos-metiers/transformation-des-organisations/animateur-de-rencontres-professionnelles/"

[[redirects]]
from = "/nos-metiers/mentorat/index.html"
to = "/nos-metiers/accompagnement-individuel-1/mentor/"

[[redirects]]
from = "/personnes/equipe-editoriale/index.html"
to = "/qui-sommes-nous-1/equipe-editoriale/"

[[redirects]]
from = "/expertises/pierre-yves-legrand/index.html"
to = "/qui-sommes-nous-1/pierre-yves-legrand/"

[[redirects]]
from = "/secteurs/rse-toutes-entreprises/index.html"
to = "/secteurs/rse/"

[[redirects]]
from = "/nos-metiers/transformation-des-organisations/podcast/index.html"
to = "/nos-metiers/transformation-des-organisations/podcasteur/"

[[redirects]]
from = "/nos-metiers/transformation-des-organisations/animateur-dateliers-de-sensibilisation-a-larchitecture-et-a-lurbanisme-regeneratifs/index.html"
to = "/nos-metiers/transformation-des-organisations/vulgarisateur/"

[[redirects]]
from = "/accompagnement-a-la-structuration-de-filiere/index.html"
to = "/nos-metiers/transformation-des-organisations/accompagnement-a-la-structuration-de-filiere/"

[[redirects]]
from = "/nos-metiers/accompagnement-individuel/index.html"
to = "/nos-metiers/accompagnement-individuel-1/mentor/"

[[redirects]]
from = "/pierre-yves-legrand/index.html"
to = "/qui-sommes-nous-1/pierre-yves-legrand/"

[[redirects]]
from = "/nos-metiers/transformation-des-organisations/animer-des-dynamiques-collectives-de-communautes/index.html"
to = "/nos-metiers/transformation-des-organisations/animateur-de-reseaux-et-de-communautes/"

[[redirects]]
from = "/expositions/archives-expositions/index.html"
to = "/inspirations/archives-expositions/"

[[redirects]]
from = "/references/index.html"
to = "/actualites/"

[[redirects]]
from = "/nos-metiers/transformation-des-organisations/consultant-en-prospective-et-strategie/index.html"
to = "/nos-metiers/transformation-des-organisations/consultant-en-strategie-et-prospective/"

[[redirects]]
from = "/nos-metiers/transformation-des-organisations/conseil-en-prospective-et-strategie/index.html"
to = "/nos-metiers/transformation-des-organisations/consultant-en-strategie-et-prospective/"

[[redirects]]
from = "/nos-metiers/transformation-des-organisations/conseil-editorial-1/index.html"
to = "/nos-metiers/transformation-des-organisations/conseiller-editorial/"

[[redirects]]
from = "/nos-metiers/transformation-des-organisations/mediation-de-connaissance/index.html"
to = "/nos-metiers/transformation-des-organisations/mediateur-de-connaissance/"

[[redirects]]
from = "/personnes/index.html"
to = "/qui-sommes-nous-1/"

[[redirects]]
from = "/secteurs/construction/index.html"
to = "/secteurs/construction-immobilier-amenagement-urbanisme/"

[[redirects]]
from = "/nos-metiers/transformation-des-organisations/relations-publiques/index.html"
to = "/nos-metiers/transformation-des-organisations/charge-de-relations-publiques/"

[[redirects]]
from = "/secteurs/energie/index.html"
to = "/secteurs/energies/"

[[redirects]]
from = "/mediation-de-connaissance/index.html"
to = "/nos-metiers/transformation-des-organisations/mediateur-de-connaissance/"

[[redirects]]
from = "/expertises-1/index.html"
to = "/expertises/"

[[redirects]]
from = "/nos-missions/index.html"
to = "/qui-sommes-nous-1/nos-missions/"

[[redirects]]
from = "/nos-metiers/transformation-des-organisations/accompagner-lemergence-de-linnovation/index.html"
to = "/nos-metiers/transformation-des-organisations/facilitateur-d-innovation/"

[[redirects]]
from = "/actualites/mentorat/index.html"
to = "/actualites/metiers/mentorat/"

